# Generated by Django 4.1.4 on 2022-12-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elems_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Elems_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_2', models.ImageField(upload_to='')),
                ('title_2', models.CharField(max_length=200)),
                ('description_2', models.CharField(max_length=300)),
                ('price_2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Elems_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_3', models.ImageField(upload_to='')),
                ('title_3', models.CharField(max_length=200)),
                ('description_3', models.CharField(max_length=300)),
                ('price_3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Elems_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_4', models.ImageField(upload_to='')),
                ('title_4', models.CharField(max_length=200)),
                ('description_4', models.CharField(max_length=300)),
                ('price_4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Elems_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_5', models.ImageField(upload_to='')),
                ('title_5', models.CharField(max_length=200)),
                ('description_5', models.CharField(max_length=300)),
                ('price_5', models.FloatField()),
            ],
        ),
    ]
