# Generated by Django 4.1.4 on 2022-12-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cas_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elems_5',
        ),
    ]
