# Generated by Django 4.1.4 on 2022-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas_blog', '0004_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='image_per',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
